name: validate dev branch and promote

on:
  push:
    branches: [ "dev" ]     
  workflow_dispatch:             

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch just enough history for a two‑dot diff
          fetch-depth: 2

      - name: Get changed .slp files (git diff)
        id: diff
        shell: bash
        run: |
          # If it's the very first commit on the branch, before may be all zeros.
          BEFORE="${{ github.event.before }}"
          if [[ "$BEFORE" == "0000000000000000000000000000000000000000" ]]; then
            # Fall back to the parent of HEAD so diff still works.
            BEFORE=$(git rev-parse HEAD^)
          fi

          # List added/modified/renamed *.slp files between BEFORE…HEAD
          CHANGED=$(git diff --name-only "$BEFORE" ${{ github.sha }} -- '*.slp')

          # Expose as a multiline output
          {
            echo 'changed_files<<EOF'
            echo "$CHANGED"
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Validate pipelines
        if: steps.diff.outputs.changed_files != ''
        shell: bash
        run: |
          files="${{ steps.diff.outputs.changed_files }}"
          count=$(echo "$files" | grep -c .)   # number of non‑empty lines

          echo "Changed .slp files:"
          if [ "$count" -gt 1 ]; then
            while IFS= read -r f; do
              echo "• $f"
              # ./scripts/validate "$f"
            done <<< "$files"
          else
            echo "• $files"
            # ./scripts/validate "$files"
          fi

      - name: No pipeline changes
        if: steps.diff.outputs.changed_files == ''
        run: echo "No .slp files changed – skipping validation."
