name: validate dev branch and promote

on:
  push:
    branches: [ "dev" ]
    # paths:
    #   - "**/*.slp" # only fire when a .slp file is in the diff
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed .slp files
        id: changed
        uses: tj-actions/changed-files@v44
        with:
          files: "**/*.slp"

      - name: Validate pipelines
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          echo "Changed .slp files:"
          files="${{ steps.changed.outputs.all_changed_files }}"
      
          # How many paths did we get?
          count=$(echo "$files" | wc -l)
      
          if [ "$count" -gt 1 ]; then
            # ➜ more than one file: loop over each
            for file in $files; do
              echo "• $file"
              # ./scripts/validate "$file"
            done
          else
            # ➜ exactly one file: just print/validate once
            echo "• $files"
            # ./scripts/validate "$files"
          fi

      - name: Determine Asset Changes
        run: echo "Test"
